channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.6
  - biopython=1.70
  - trim-galore=0.4.5
  - snakemake=5.1.4
  - star=2.6.0c
  - fastqc=0.11.7
  - qualimap=2.2.2a
  - multiqc=1.5
  - bwa=0.7.17
  - minimap2=2.11