name: virusMAP
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.70=np112py36_1
  - trim-galore=0.4.5=2
  - snakemake=5.1.4=py36_2
  - star=2.6.0c=1
  - fastqc=0.11.7=pl5.22.0_1
  - qualimap=2.2.2a=2
  - multiqc=1.5=py36_0